wallpaper {
    monitor = HDMI-A-1
    path = /home/ozbay/Images/bg-hdmi.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/ozbay/Images/bg-dp.png
    fit_mode = cover
}

splash = false
